apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: socketio-test-service-env
  namespace: socketio-namespace
spec:
  refreshInterval: 1m
  secretStoreRef:
    kind: SecretStore
    name: vault-kv
  target:
    name: socketio-test-service-env
    creationPolicy: Owner
  data:
    - secretKey: TEST__LOGIN_VAR
      remoteRef:
        key: socketio-test-service
        property: TEST__LOGIN_VAR
    - secretKey: TEST_PASSWORD_VAR
      remoteRef:
        key: socketio-test-service
        property: TEST_PASSWORD_VAR
